import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ToasterProvider from "@/components/providers/toaster-provider";
import LoginModalProvider from "@/components/providers/login-modal-provider";
import ClientModalProvider from "@/components/providers/client-modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Norte Digital Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <LoginModalProvider />
        <ClientModalProvider />
        {children}
      </body>
    </html>
  );
}
